### ISSUE TITLE
setIcon(new javax.swing.ImageIcon(getClass().getResource  java.lang.NullPointerException

### ISSUE THREAD

**Issue by wfrsilva** [wfrsilva/javaMySQL03_infoX#1]
`lblStatus.setIcon(new javax.swing.ImageIcon(
"Z:\\java\\javaMySQL03_infoX\\src\\main\\java\\br\\com\\infox\\icones\\dbok.png")); `

Is OK!

But this:

`lblStatus.setIcon(new javax.swing.ImageIcon(
getClass().getResource("/br/com/infox/icones/dbok.png")));`

make ERROR:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at br.com.infox.telas.TelaLogin.<init>(TelaLogin.java:20)
	at br.com.infox.telas.TelaLogin$1.run(TelaLogin.java:124)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
```

My project is running with Maven

In https://stackoverflow.com/questions/14593766/getclass-getresource-exception
I used this tip : 
`System.out.println(getClass().getProtectionDomain().getCodeSource().getLocation());
`
And the print was:
`file:/Z:/java/javaMySQL03_infoX/target/classes/`

**Comment by wfrsilva** [comment]
Boa noite pessoal
Não sei mexer muito com maven e ja estou em arrependendo ...

Se uso o caminho relativo, conforme aula:lblStatus.setIcon(new javax.swing.ImageIcon( getClass().getResource("/br/com/infox/icones/dbok.png"))); 

Ocorre o erro:
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:217)	at br.com.infox.telas.TelaLogin.<init>(TelaLogin.java:20)	at br.com.infox.telas.TelaLogin$1.run(TelaLogin.java:124)	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)  at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
Se uso o caminho real:
 lblStatus.setIcon(new javax.swing.ImageIcon( "Z:\\java\\javaMySQL03_infoX\\src\\main\\java\\br\\com\\infox\\icones\\dbok.png"));

funciona, mas obvio que se gerar um JAR e rodar em outra maquina não vai funcionar.

vi uma dica no s.o.flow:https://stackoverflow.com/questions/14593766/getclass-getresource-exception 

e usei esse print:
 System.out.println(getClass().getProtectionDomain().getCodeSource().getLocation());

me retornando esse endereço:
file:/Z:/java/javaMySQL03_infoX/target/classes/ 

Projeto original esta nesse:
 z:/java/javaMySQL03_infoX/src/main/java/br/com/infox/icones

então o maven esta salvando as CLASS nesse target, mas não esta levando os ícones, como arrumo isso?

**Comment by wfrsilva** [comment]
https://pt.stackoverflow.com/questions/432671/conflito-diretorio-maven-seticonnew-javax-swing-imageicongetclass-getresourc

**Comment by wfrsilva** [comment]
Diego Henrique diegosource@gmail.com [java-br] <java-br@yahoogrupos.com.br> | Diego Henrique diegosource@gmail.com [java-br] <java-br@yahoogrupos.com.br> | 27 de jan. de 2020 08:42 |   |  
-- | -- | -- | -- | --
Diego Henrique diegosource@gmail.com [java-br] <java-br@yahoogrupos.com.br>
para java-br | para java-br
para java-br

**Comment by wfrsilva** [comment]
Diego Henrique diegosource@gmail.com [java-br] <java-br@yahoogrupos.com.br>
27 de jan. de 2020 08:42
para java-br

Oi,

Primeiro, maven é uma ferramenta de build madura, e provavelmente irá comtemplar 99,9% dos seus casos de build. Se vc estiver insatisfeito com ele pode usar outras ferramentas como: gradle, ivy, ant, entre outras.

Vou te dar umas dicas para esse problema.

1. Pegue  o jar gerado descompacte ele e veja se os recursos de imagens foram exportados para dentro do jar no processo de build.
1.1 Se foram exportados vc precisa buscar pelo caminho relativo e não absoluto.
2. Se não foram exportados vc precisa adicionar filtros específicos para isso no pom.xml. [Entenda mais sobre os filtros aqui](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html)

[Aqui ](https://stackoverflow.com/questions/45751561/how-can-i-add-images-in-source-folder-of-a-maven-java-project)provavelmente encontra-se a solução para o seu problema.

**Comment by wfrsilva** [comment]
https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html

Solução aplicada no POM.xml:
    
```
          <resources>
              <resource>
                 <directory>src/main/java/</directory>
              </resource>
        </resources>
```


Aparentemente resolveu
